# Generated by Django 6.0.5 on 2026-10-03 14:40

import apps.core.storage
import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_logo_user_branding_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, help_text="Business logo shown on this photographer's public gallery pages.", null=True, storage=apps.core.storage.PublicMediaStorage(), upload_to=apps.users.models.get_branding_logo_path),
        ),
    ]
