# Generated by Django 6.0.5 on 2026-10-03 15:25

import apps.core.storage
import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collection_defaults',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_downloads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_favorites',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_payments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=apps.core.storage.PublicMediaStorage(), upload_to=apps.users.models.get_profile_avatar_path),
        ),
    ]
