# Generated by Django 6.0.5 on 2026-10-03 16:03

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0008_backfill_trashed_at'),
        ('users', '0005_settings_privacy_notifications_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('download', 'Download'), ('favorite', 'Favorite'), ('payment', 'Payment'), ('published', 'Gallery published'), ('processing_done', 'Processing complete'), ('processing_failed', 'Processing failed')], max_length=20)),
                ('message', models.CharField(max_length=300)),
                ('count', models.PositiveIntegerField(default=1)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='galleries.gallery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-updated_at'], name='idx_notif_user_read_updated')],
            },
        ),
    ]
