# Generated by Django 6.0.5 on 2026-10-06 13:05

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('download', 'Download'), ('favorite', 'Favorite'), ('payment', 'Payment'), ('published', 'Gallery published'), ('processing_done', 'Processing complete'), ('processing_failed', 'Processing failed'), ('feedback', 'New feedback')], max_length=20),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('feature_request', 'Feature request'), ('design', 'Design'), ('performance', 'Performance'), ('download', 'Download'), ('upload', 'Upload'), ('security_privacy', 'Security / privacy'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('route', models.CharField(blank=True, default='', max_length=200)),
                ('gallery_slug', models.CharField(blank=True, default='', max_length=225)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('browser_class', models.CharField(choices=[('chrome', 'Chrome'), ('edge', 'Edge'), ('firefox', 'Firefox'), ('safari', 'Safari'), ('opera', 'Opera'), ('other', 'Other')], default='other', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='new', max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='idx_feedback_status_created'), models.Index(fields=['user', '-created_at'], name='idx_feedback_user_created')],
            },
        ),
    ]
