# Generated by Django 6.0.5 on 2026-10-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('download', 'Download'), ('favorite', 'Favorite'), ('payment', 'Payment'), ('published', 'Gallery published'), ('processing_done', 'Processing complete'), ('processing_failed', 'Processing failed'), ('feedback', 'New feedback'), ('security', 'Security alert')], max_length=20),
        ),
    ]
