# Generated by Django 6.0.5 on 2026-10-08 09:04

from django.db import migrations, models


FUNCTION_SQL = """
CREATE OR REPLACE FUNCTION staff_audit_log_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'staff_audit_log is append-only';
END;
$$ LANGUAGE plpgsql;
"""
TRIGGER_SQL = """
CREATE TRIGGER staff_audit_log_no_change
BEFORE UPDATE OR DELETE ON staff_audit_log
FOR EACH ROW EXECUTE FUNCTION staff_audit_log_append_only();
"""


def add_append_only_trigger(apps, schema_editor):
    """The database itself refuses UPDATE and DELETE of an audit row (PostgreSQL; TRUNCATE is not row-level)."""
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(FUNCTION_SQL)
    schema_editor.execute(TRIGGER_SQL)


def drop_append_only_trigger(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute('DROP TRIGGER IF EXISTS staff_audit_log_no_change ON staff_audit_log')
    schema_editor.execute('DROP FUNCTION IF EXISTS staff_audit_log_append_only()')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_password_reset_and_token_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suspended_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.CharField(blank=True, default='', editable=False, max_length=300),
        ),
        migrations.CreateModel(
            name='StaffAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('staff.user_list', 'Viewed the user list'), ('staff.user_lookup', 'Looked up a user by email'), ('staff.audit_view', 'Viewed the audit log'), ('account.suspend', 'Suspended an account'), ('account.reactivate', 'Reactivated an account'), ('staff.feedback_status', 'Changed a feedback status'), ('staff.payment_review', 'Reviewed a manual payment'), ('staff.inbox_view', 'Viewed a staff queue'), ('security.login_lockout', 'Login locked'), ('security.gallery_lockout', 'Gallery gate locked'), ('security.password_reset', 'Password reset'), ('security.password_change', 'Password changed')], db_index=True, max_length=30)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('target_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('target_email', models.EmailField(blank=True, default='', max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'db_table': 'staff_audit_log',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['actor_id', '-created_at'], name='idx_audit_actor_created')],
            },
        ),
        migrations.RunPython(add_append_only_trigger, drop_append_only_trigger),
    ]
