# Generated by Django 6.0.5 on 2026-10-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_staff_audit_log_and_suspension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('download', 'Download'), ('favorite', 'Favorite'), ('payment', 'Payment'), ('published', 'Gallery published'), ('processing_done', 'Processing complete'), ('processing_failed', 'Processing failed'), ('feedback', 'New feedback'), ('security', 'Security alert'), ('payment_review', 'Payment to review')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffauditlog',
            name='action',
            field=models.CharField(choices=[('staff.user_list', 'Viewed the user list'), ('staff.user_lookup', 'Looked up a user by email'), ('staff.audit_view', 'Viewed the audit log'), ('account.suspend', 'Suspended an account'), ('account.reactivate', 'Reactivated an account'), ('staff.feedback_status', 'Changed a feedback status'), ('staff.payment_review', 'Reviewed a manual payment'), ('payment.approve', 'Approved a manual payment'), ('payment.reject', 'Rejected a manual payment'), ('payment.proof_view', 'Opened a payment proof'), ('staff.inbox_view', 'Viewed a staff queue'), ('security.login_lockout', 'Login locked'), ('security.gallery_lockout', 'Gallery gate locked'), ('security.password_reset', 'Password reset'), ('security.password_change', 'Password changed'), ('payment.submit', 'Submitted a manual payment')], db_index=True, max_length=30),
        ),
    ]
