# Generated by Django 6.0.5 on 2026-10-09 11:37

import django.core.validators
from django.db import migrations, models


def create_row(apps, schema_editor):
    """The one AccountSettings row exists from the start, so reading it is a single query (no lazy create)."""
    apps.get_model('users', 'AccountSettings').objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_subscription_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('deletion_cooling_off_days', models.PositiveSmallIntegerField(default=7, help_text='Days between a deletion request and the purge. The account can cancel in this time. 0 starts the purge immediately (no way back). Maximum 90.', validators=[django.core.validators.MaxValueValidator(90)], verbose_name='Deletion cooling-off days (DELETION_COOLING_OFF_DAYS)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account settings',
                'verbose_name_plural': 'Account settings',
                'db_table': 'account_settings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_cancel_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_scheduled_for',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='staffauditlog',
            name='action',
            field=models.CharField(choices=[('staff.user_list', 'Viewed the user list'), ('staff.user_lookup', 'Looked up a user by email'), ('staff.audit_view', 'Viewed the audit log'), ('account.suspend', 'Suspended an account'), ('account.reactivate', 'Reactivated an account'), ('staff.feedback_status', 'Changed a feedback status'), ('staff.payment_review', 'Reviewed a manual payment'), ('payment.approve', 'Approved a manual payment'), ('payment.reject', 'Rejected a manual payment'), ('payment.proof_view', 'Opened a payment proof'), ('staff.inbox_view', 'Viewed a staff queue'), ('security.login_lockout', 'Login locked'), ('security.gallery_lockout', 'Gallery gate locked'), ('security.password_reset', 'Password reset'), ('security.password_change', 'Password changed'), ('payment.submit', 'Submitted a manual payment'), ('subscription.downgrade', 'Moved to Free after the plan ended'), ('account.deletion_requested', 'Requested account deletion'), ('account.deletion_cancelled', 'Cancelled account deletion'), ('account.deletion_completed', 'Account deleted')], db_index=True, max_length=30),
        ),
        migrations.RunPython(create_row, migrations.RunPython.noop),
    ]
