# Generated by Django 6.0.5 on 2026-10-06 10:36

import django.core.validators
from django.db import migrations, models


def create_row(apps, schema_editor):
    """The single row, with the model's defaults (load() also creates it if it is ever missing)."""
    apps.get_model('subscriptions', 'UploadLimits').objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_free_collection_cap_drop_photo_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLimits',
            fields=[
                ('id', models.PositiveSmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('max_image_mb', models.PositiveIntegerField(default=100, help_text='A photo larger than this is refused before it is processed.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max image size (MB)')),
                ('max_image_pixels', models.PositiveBigIntegerField(default=144000000, help_text='A photo with more pixels than this is refused from its header, before it is decoded.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max image pixels (width x height)')),
                ('max_video_mb', models.PositiveIntegerField(default=2048, help_text="A video larger than this is refused. The web server's client_max_body_size must be at least this plus overhead (see docs/KYAPTURE_UPLOAD_LIMITS.md).", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max video size (MB)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Upload limits',
                'verbose_name_plural': 'Upload limits',
                'db_table': 'upload_limits',
            },
        ),
        migrations.RunPython(create_row, migrations.RunPython.noop),
    ]
