# Generated by Django 6.0.5 on 2026-10-08 11:49

import apps.core.storage
import apps.subscriptions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_upload_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInstructions',
            fields=[
                ('id', models.PositiveSmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(blank=True, default='', max_length=100)),
                ('esewa_id', models.CharField(blank=True, default='', max_length=60, verbose_name='eSewa ID / number')),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=60)),
                ('bank_branch', models.CharField(blank=True, default='', max_length=100)),
                ('qr_image', models.ImageField(blank=True, help_text='Optional. PNG, JPEG or WEBP, public: anyone with the link can see it.', null=True, storage=apps.core.storage.PublicMediaStorage(), upload_to=apps.subscriptions.models.get_payment_qr_upload_path, verbose_name='QR image')),
                ('note', models.TextField(blank=True, default='', help_text='Short plain-text note shown above the payment form (for example how long a review takes).', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment instructions',
                'verbose_name_plural': 'Payment instructions',
                'db_table': 'payment_instructions',
            },
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='currency',
            field=models.CharField(default='NPR', max_length=3),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='plan_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='proof_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='proof_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='reference_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manualpayment',
            name='payment_proof',
            field=models.FileField(storage=apps.core.storage.PrivateMediaStorage(), upload_to=apps.subscriptions.models.get_payment_proof_upload_path),
        ),
    ]
