# Generated by Django 6.0.5 on 2026-10-08 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_manual_payment_reference_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('reminder_days', models.PositiveSmallIntegerField(default=3, help_text='One reminder (bell and email) goes out this many days before a paid period ends.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Reminder days before the end')),
                ('grace_days', models.PositiveSmallIntegerField(default=3, help_text='After this many full days past the end the account is moved to Free and told. Paid features stop at the end of the period regardless; files are never deleted.', validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Grace days after the end')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription lifecycle',
                'verbose_name_plural': 'Subscription lifecycle',
                'db_table': 'subscription_lifecycle_settings',
            },
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='downgrade_emailed_for',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='downgraded_for',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='reminder_emailed_for',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='reminder_notified_for',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
