# Generated by Django 6.0.5 on 2026-05-28 05:37

import apps.clients.models
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, help_text='Optional email provided by client for download tracking or newsletter leads.', max_length=254, null=True)),
                ('access_token', models.CharField(default=apps.clients.models.generate_secure_token, editable=False, max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Auditable IP address of the client device.', null=True)),
                ('has_download_access', models.BooleanField(default=False, help_text='Tracks whether this specific client session is permitted to trigger gallery downloads.')),
            ],
            options={
                'db_table': 'client_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
