# Generated by Django 6.0.5 on 2026-05-28 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsession',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to='galleries.gallery'),
        ),
        migrations.AddIndex(
            model_name='clientsession',
            index=models.Index(fields=['access_token', 'created_at'], name='idx_client_token_lookup'),
        ),
    ]
