# Generated by Django 6.0.5 on 2026-07-18 09:38

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('galleries', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Enforced client email required to initiate a gallery archive download.', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Auditable IP address of the client device requesting the download.', null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='galleries.gallery')),
            ],
            options={
                'db_table': 'download_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gallery', 'created_at'], name='idx_download_gallery_date')],
            },
        ),
    ]
