# Generated by Django 6.0.5 on 2026-09-30 03:06

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_downloadlog'),
        ('galleries', '0006_gallery_download_pin_hash'),
        ('photos', '0003_photoset_mediaasset_photo_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='download_type',
            field=models.CharField(choices=[('gallery', 'Full Gallery'), ('photo', 'Single Photo'), ('video', 'Single Video')], default='gallery', max_length=10),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='media_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_logs', to='photos.mediaasset'),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='photo_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_logs', to='photos.photoset'),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='pin_verified',
            field=models.BooleanField(default=False, help_text="Whether this download required and passed the gallery's optional download PIN gate."),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='resolution',
            field=models.CharField(choices=[('web', 'Web Size'), ('original', 'High Resolution')], default='original', help_text='Which derivative was actually served: the web-optimized display file, or the authorized full-resolution original.', max_length=10),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_key', models.CharField(help_text="Stable per-client identifier: the gallery's access_token for protected galleries, or a client-generated anonymous id for open galleries.", max_length=128)),
                ('email', models.EmailField(blank=True, help_text="Copied from the client session's email when available, for photographer-facing favorite activity.", max_length=254, null=True)),
                ('client_session', models.ForeignKey(blank=True, help_text='Set only for password-protected galleries, where a real ClientSession already exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites', to='clients.clientsession')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='galleries.gallery')),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='photos.mediaasset')),
            ],
            options={
                'db_table': 'favorites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gallery', 'client_key'], name='idx_favorite_gallery_client'), models.Index(fields=['media_asset'], name='idx_favorite_media_asset')],
                'constraints': [models.UniqueConstraint(fields=('gallery', 'media_asset', 'client_key'), name='unique_favorite_per_client_asset')],
            },
        ),
    ]
