# Generated by Django 6.0.5 on 2026-09-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_downloadlog_download_type_downloadlog_media_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='email',
            field=models.EmailField(blank=True, help_text='Client email — required for a gallery ZIP download (lead capture), null for a frictionless single-photo/video download.', max_length=254, null=True),
        ),
    ]
