# Generated by Django 6.0.5 on 2026-10-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_downloadlog_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='resolution',
            field=models.CharField(
                choices=[
                    ('web', 'Web Size'),
                    ('download', 'Download Master'),
                    ('original', 'High Resolution'),
                ],
                default='original',
                help_text='Which derivative was actually served: the web-optimized display file, optimized download master, or authorized original.',
                max_length=10,
            ),
        ),
    ]
