# Generated by Django 6.0.5 on 2026-10-03 19:19

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_downloadlog_resolution'),
        ('galleries', '0008_backfill_trashed_at'),
        ('photos', '0006_mediaasset_watermark_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolution', models.CharField(default='download', max_length=10)),
                ('asset_ids', models.JSONField(blank=True, default=list)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pin_verified', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('preparing', 'Preparing'), ('ready', 'Ready'), ('failed', 'Failed')], default='preparing', max_length=10)),
                ('error_code', models.CharField(blank=True, default='', max_length=40)),
                ('files', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('download_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='clients.downloadlog')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_jobs', to='galleries.gallery')),
                ('photo_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_jobs', to='photos.photoset')),
            ],
            options={
                'db_table': 'download_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gallery', 'state'], name='idx_djob_gallery_state'), models.Index(fields=['expires_at'], name='idx_djob_expires')],
            },
        ),
    ]
