# Generated by Django 6.0.5 on 2026-10-03 20:48

import django.db.models.deletion
import uuid6
from django.db import migrations, models


def backfill_default_lists(apps, schema_editor):
    """
    Every existing visitor (gallery + client_key) gets one default "My Favorites"
    list holding their current favorites. The visitor's email is the first one
    recorded on their favorites, else the one on their unlock session; a visitor
    who never gave an email stays a guest (email NULL) - nothing is invented.
    """
    Favorite = apps.get_model('clients', 'Favorite')
    FavoriteList = apps.get_model('clients', 'FavoriteList')
    ClientSession = apps.get_model('clients', 'ClientSession')

    groups = Favorite.objects.filter(favorite_list__isnull=True).values_list('gallery_id', 'client_key').distinct()
    for gallery_id, client_key in list(groups):
        rows = Favorite.objects.filter(gallery_id=gallery_id, client_key=client_key, favorite_list__isnull=True)
        email = rows.exclude(email__isnull=True).exclude(email='').values_list('email', flat=True).first()
        if not email:
            email = (
                ClientSession.objects.filter(gallery_id=gallery_id, access_token=client_key)
                .exclude(email__isnull=True).exclude(email='').values_list('email', flat=True).first()
            )
        favorite_list, _ = FavoriteList.objects.get_or_create(
            gallery_id=gallery_id, client_key=client_key, name='My Favorites',
            defaults={'email': email or None, 'is_default': True},
        )
        rows.update(favorite_list=favorite_list, **({'email': email} if email else {}))


def unfill_default_lists(apps, schema_editor):
    apps.get_model('clients', 'Favorite').objects.update(favorite_list=None)
    apps.get_model('clients', 'FavoriteList').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_download_jobs_and_log_filename'),
        ('galleries', '0008_backfill_trashed_at'),
        ('photos', '0006_mediaasset_watermark_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_key', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('visitor_name', models.CharField(blank=True, default='', max_length=80)),
                ('name', models.CharField(default='My Favorites', max_length=80)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'favorite_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_favorite_per_client_asset',
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='photo_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoritelist',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_lists', to='galleries.gallery'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='clients.favoritelist'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('favorite_list__isnull', False)), fields=('favorite_list', 'media_asset'), name='unique_favorite_per_list_asset'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('favorite_list__isnull', True)), fields=('gallery', 'media_asset', 'client_key'), name='unique_favorite_per_client_asset'),
        ),
        migrations.AddIndex(
            model_name='favoritelist',
            index=models.Index(fields=['gallery', 'client_key'], name='idx_favlist_gallery_client'),
        ),
        migrations.AddConstraint(
            model_name='favoritelist',
            constraint=models.UniqueConstraint(fields=('gallery', 'client_key', 'name'), name='unique_favorite_list_name'),
        ),
        migrations.RunPython(backfill_default_lists, unfill_default_lists),
    ]
