# Generated by Django 6.0.5 on 2026-10-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_favorite_lists_and_download_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadjob',
            name='ready_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadjob',
            name='requester_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
