# Generated by Django 6.0.5 on 2026-10-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_one_default_list_per_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadjob',
            name='variant',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
