# Generated by Django 6.0.5 on 2026-10-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_hash_unlock_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='client_key',
            field=models.CharField(help_text="Stable per-client identifier: the browser's client_uid, or for a protected gallery without one the unlock session's stored token hash (never the token itself).", max_length=128),
        ),
    ]
