# Generated by Django 6.0.5 on 2026-05-28 05:37

import apps.photos.models
import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.photos.models.get_photo_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.photos.models.get_thumbnail_upload_path)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='galleries.gallery')),
            ],
            options={
                'db_table': 'photos',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['gallery', 'order'], name='idx_gallery_photos_order'), models.Index(fields=['created_at'], name='idx_photos_created_at')],
            },
        ),
    ]
