# Generated by Django 6.0.5 on 2026-06-10 09:41

import apps.photos.models
import django.db.models.deletion
import uuid6
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('order', models.DecimalField(decimal_places=10, default=Decimal('1.0'), max_digits=20)),
                ('original_file', models.FileField(max_length=500, upload_to=apps.photos.models.get_original_asset_path)),
                ('display_file', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.photos.models.get_display_photo_path)),
                ('thumbnail_file', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.photos.models.get_thumbnail_photo_path)),
                ('blurhash', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('stream_url', models.URLField(blank=True, max_length=500, null=True)),
                ('poster_image', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.photos.models.get_video_poster_path)),
                ('preview_file', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.photos.models.get_video_preview_path)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='galleries.gallery')),
            ],
            options={
                'db_table': 'media_assets',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['gallery', 'order'], name='idx_gallery_assets_order'), models.Index(fields=['gallery', 'media_type'], name='idx_gallery_assets_type'), models.Index(fields=['created_at'], name='idx_assets_created_at'), models.Index(fields=['processing_status'], name='idx_assets_proc_status')],
            },
        ),
    ]
