# Generated by Django 6.0.5 on 2026-09-29 20:38

import apps.core.storage
import apps.photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='medium_file',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=apps.core.storage.PublicMediaStorage(), upload_to=apps.photos.models.get_medium_photo_path),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='playback_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=apps.core.storage.PublicMediaStorage(), upload_to=apps.photos.models.get_video_playback_path),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='display_file',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=apps.core.storage.PublicMediaStorage(), upload_to=apps.photos.models.get_display_photo_path),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='original_file',
            field=models.FileField(max_length=500, storage=apps.core.storage.PrivateMediaStorage(), upload_to=apps.photos.models.get_original_asset_path),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='poster_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=apps.core.storage.PublicMediaStorage(), upload_to=apps.photos.models.get_video_poster_path),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='preview_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=apps.core.storage.PublicMediaStorage(), upload_to=apps.photos.models.get_video_preview_path),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='thumbnail_file',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=apps.core.storage.PublicMediaStorage(), upload_to=apps.photos.models.get_thumbnail_photo_path),
        ),
    ]
