# Generated by Django 6.0.5 on 2026-09-30 03:06

import django.db.models.deletion
import uuid6
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0006_gallery_download_pin_hash'),
        ('photos', '0002_mediaasset_medium_file_mediaasset_playback_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSet',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.DecimalField(decimal_places=10, default=Decimal('1.0'), max_digits=20)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_sets', to='galleries.gallery')),
            ],
            options={
                'db_table': 'photo_sets',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='photo_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='photos.photoset'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['photo_set', 'order'], name='idx_set_assets_order'),
        ),
        migrations.AddIndex(
            model_name='photoset',
            index=models.Index(fields=['gallery', 'order'], name='idx_gallery_sets_order'),
        ),
        migrations.AddConstraint(
            model_name='photoset',
            constraint=models.UniqueConstraint(fields=('gallery', 'name'), name='unique_gallery_photoset_name'),
        ),
    ]
