# Generated by Django 6.0.5 on 2026-09-30 19:03

import django.db.models.deletion
from django.db import migrations, models


def backfill_highlights_sets(apps, schema_editor):
    """Safely establish the default set without disturbing existing membership."""
    Gallery = apps.get_model('galleries', 'Gallery')
    PhotoSet = apps.get_model('photos', 'PhotoSet')
    MediaAsset = apps.get_model('photos', 'MediaAsset')

    for gallery in Gallery.objects.filter(is_active=True).iterator():
        highlights, _ = PhotoSet.objects.get_or_create(
            gallery_id=gallery.id,
            name='Highlights',
            defaults={'order': 1},
        )
        MediaAsset.objects.filter(
            gallery_id=gallery.id,
            photo_set__isnull=True,
        ).update(photo_set_id=highlights.id)


def noop_reverse(apps, schema_editor):
    """Existing set memberships must remain intact when rolling back schema state."""


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0008_backfill_trashed_at'),
        ('photos', '0003_photoset_mediaasset_photo_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoset',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='photo_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='photos.photoset'),
        ),
        migrations.AlterField(
            model_name='photoset',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='galleries.gallery'),
        ),
        migrations.RunPython(backfill_highlights_sets, noop_reverse),
    ]
