# Generated by Django 6.0.5 on 2026-10-02

import apps.core.storage
import apps.photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photoset_v2_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='download_file',
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                storage=apps.core.storage.PrivateMediaStorage(),
                upload_to=apps.photos.models.get_download_photo_path,
            ),
        ),
    ]
