# Generated by Django 6.0.5 on 2026-10-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_mediaasset_download_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='watermark_signature',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
