# Generated by Django 6.0.5 on 2026-10-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0008_backfill_trashed_at'),
        ('photos', '0006_mediaasset_watermark_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='favorited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(condition=models.Q(('is_favorite', True)), fields=['gallery', 'favorited_at'], name='idx_assets_favorites'),
        ),
    ]
