# Generated by Django 6.0.5 on 2026-10-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    media_assets.file_size: 32-bit integer -> 64-bit bigint (a 2-5 GB video overflowed it).

    No data is changed or lost: every existing value widens as-is, and the CHECK (>= 0)
    constraint stays. On Postgres this is one `ALTER COLUMN ... TYPE bigint`, which rewrites
    the table under a short ACCESS EXCLUSIVE lock; run it in a quiet window on a large table.

    Reversible, with one guard: reversing narrows the column back to 32 bits, and Postgres
    refuses ("integer out of range") while any row holds a value above 2,147,483,647, so
    a reverse can never silently truncate a size.
    """

    dependencies = [
        ('photos', '0007_mediaasset_photographer_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='file_size',
            field=models.PositiveBigIntegerField(),
        ),
    ]
