import { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Quote, ChevronLeft, ChevronRight, Star } from 'lucide-react';

const stats = [
  { value: '10M+', label: 'Photos Delivered', icon: '📸' },
  { value: '99.9%', label: 'Uptime Guarantee', icon: '⚡' },
  { value: '$5M+', label: 'Generated by Photographers', icon: '💰' },
];

const testimonials = [
  {
    quote:
      'Kyapture transformed how I deliver galleries to clients. The proofing experience is seamless and my clients absolutely love it. It elevated my entire brand.',
    name: 'Sarah Mitchell',
    role: 'Wedding Photographer',
    avatar: 'SM',
    rating: 5,
  },
  {
    quote:
      'The AI culling tool alone saved me 4 hours per shoot. Combined with the studio manager, I have my weekends back for the first time in years.',
    name: 'James Ortega',
    role: 'Commercial Photographer',
    avatar: 'JO',
    rating: 5,
  },
  {
    quote:
      'I replaced four different tools with Kyapture. The portfolio builder is gorgeous, and the invoicing makes getting paid effortless.',
    name: 'Lena Park',
    role: 'Editorial Photographer',
    avatar: 'LP',
    rating: 5,
  },
  {
    quote:
      'My clients used to ask where their photos were every week. Now they track proofing in real-time through Kyapture. Zero follow-ups needed.',
    name: 'David Chen',
    role: 'Portrait & Family Photographer',
    avatar: 'DC',
    rating: 5,
  },
];

export default function StatsTestimonials() {
  const [currentTestimonial, setCurrentTestimonial] = useState(0);

  const next = useCallback(() => {
    setCurrentTestimonial((prev) => (prev + 1) % testimonials.length);
  }, []);

  const prev = useCallback(() => {
    setCurrentTestimonial((prev) => (prev - 1 + testimonials.length) % testimonials.length);
  }, []);

  useEffect(() => {
    const interval = setInterval(next, 5000);
    return () => clearInterval(interval);
  }, [next]);

  return (
    <section id="stats" className="py-24 bg-white">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-100px' }}
          transition={{ duration: 0.5 }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-slate-900">
            Trusted by Photographers Worldwide
          </h2>
          <p className="mt-4 text-lg text-slate-500 max-w-2xl mx-auto">
            Join a community of professional photographers who trust Kyapture to power their businesses.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-3 gap-6 mb-20">
          {stats.map((stat, i) => (
            <motion.div
              key={stat.label}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: i * 0.15 }}
              className="relative rounded-2xl bg-offwhite border border-slate-100 p-8 text-center group hover:shadow-lg hover:shadow-slate-100 transition-all duration-300"
            >
              <div className="text-4xl mb-4">{stat.icon}</div>
              <div className="text-4xl sm:text-5xl font-extrabold tracking-tight text-slate-900">
                {stat.value}
              </div>
              <div className="mt-2 text-sm font-medium text-slate-500">{stat.label}</div>
            </motion.div>
          ))}
        </div>

        <div id="testimonials" className="relative">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="relative rounded-3xl bg-offwhite border border-slate-100 p-8 sm:p-12 overflow-hidden"
          >
            <Quote className="absolute top-8 left-8 h-16 w-16 text-primary/10" />

            <div className="relative min-h-[220px]">
              <AnimatePresence mode="wait">
                <motion.div
                  key={currentTestimonial}
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -20 }}
                  transition={{ duration: 0.4 }}
                  className="flex flex-col items-center text-center"
                >
                  <div className="flex items-center gap-0.5 mb-6">
                    {[...Array(testimonials[currentTestimonial].rating)].map((_, j) => (
                      <Star key={j} className="h-4 w-4 fill-amber-400 text-amber-400" />
                    ))}
                  </div>

                  <blockquote className="text-lg sm:text-xl text-slate-700 leading-relaxed max-w-2xl font-medium">
                    "{testimonials[currentTestimonial].quote}"
                  </blockquote>

                  <div className="mt-8 flex items-center gap-4">
                    <div className="h-12 w-12 rounded-full bg-primary/10 flex items-center justify-center">
                      <span className="text-sm font-bold text-primary">
                        {testimonials[currentTestimonial].avatar}
                      </span>
                    </div>
                    <div className="text-left">
                      <div className="text-sm font-semibold text-slate-900">
                        {testimonials[currentTestimonial].name}
                      </div>
                      <div className="text-xs text-slate-500">
                        {testimonials[currentTestimonial].role}
                      </div>
                    </div>
                  </div>
                </motion.div>
              </AnimatePresence>
            </div>

            <div className="flex items-center justify-center gap-4 mt-8">
              <button
                onClick={prev}
                className="h-10 w-10 rounded-full border border-slate-200 flex items-center justify-center text-slate-400 hover:text-slate-600 hover:border-slate-300 transition-colors"
              >
                <ChevronLeft className="h-4 w-4" />
              </button>

              <div className="flex items-center gap-2">
                {testimonials.map((_, j) => (
                  <button
                    key={j}
                    onClick={() => setCurrentTestimonial(j)}
                    className={`h-2 rounded-full transition-all duration-300 ${
                      j === currentTestimonial ? 'w-6 bg-primary' : 'w-2 bg-slate-200 hover:bg-slate-300'
                    }`}
                  />
                ))}
              </div>

              <button
                onClick={next}
                className="h-10 w-10 rounded-full border border-slate-200 flex items-center justify-center text-slate-400 hover:text-slate-600 hover:border-slate-300 transition-colors"
              >
                <ChevronRight className="h-4 w-4" />
              </button>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}
