# Generated by Django 6.0.5 on 2026-05-28 05:37

import django.core.validators
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('branding_color', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid 6-character HEX code (e.g., #FFFFFF).', regex='^#[0-9a-fA-F]{6}$')])),
                ('is_password_protected', models.BooleanField(default=False)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('allow_download', models.BooleanField(default=False)),
                ('watermark_enabled', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'galleries',
                'ordering': ['-created_at'],
            },
        ),
    ]
