# Generated by Django 6.0.5 on 2026-05-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
