# Generated by Django 6.0.5 on 2026-08-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
