# Generated by Django 6.0.5 on 2026-09-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_gallery_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='design_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
