# Generated by Django 6.0.5 on 2026-09-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_gallery_design_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='download_pin_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
