# Generated by Django 6.0.5 on 2026-09-30 04:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0006_gallery_download_pin_hash'),
        ('photos', '0003_photoset_mediaasset_photo_set_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['is_active', 'trashed_at'], name='idx_gallery_trash_purge'),
        ),
    ]
